### ISSUE TITLE
After upgrading to 0.3.2, project no longer builds

### ISSUE THREAD

**Issue by geppy** [Telerik-Verified-Plugins/WKWebView#44]
The linker complains:

```
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_MyMainViewController", referenced from:
      objc-class-ref in AppDelegate+WKWebViewPolyfill.o
ld: symbol(s) not found for architecture arm64
```

**Comment by MilesYM** [comment]
I'm still having this bug, not sure I understand what this mean:
" the target membership wasn't getting set up correctly"

How to fix that ?
BrianGeppert ?

Thanks
